#!/usr/bin/env python3

import argparse
import json
from dataclasses import dataclass
from tabulate import tabulate


@dataclass
class Stat:
    statement: str
    query_time: int
    count: int


parser = argparse.ArgumentParser(description="Analyze log file generated by sqltrace.py")

parser.add_argument("file")
parser.add_argument("--sort", help="sort statistics by a given key", nargs="?", default=None)
parser.add_argument("-r", help="show statistics in inverse order", action="store_true")

args = parser.parse_args()

stats = {}

with open(args.file, "r") as fp:
    for line in fp:
        log = json.loads(line)

        if log["statement"] in stats:
            stats[log["statement"]]["query_time"] += log["query_time"]
            stats[log["statement"]]["count"] += 1
        else:
            stats[log["statement"]] = {
                "query_time": log["query_time"],
                "count": 1,
            }

stats = map(lambda p: {
    "statement": p[0][:60],
    "query_time": p[1]["query_time"],
    "count": p[1]["count"]
}, stats.items())

for key in ["query_time", "count"]:
    if key == args.sort:
        stats = sorted(stats, key=lambda s: s[key], reverse=args.r)

print(tabulate(stats))
